version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/apps/scraper"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      uv:
        patterns:
          - "*"
